### ISSUE TITLE
Family Feud

### ISSUE THREAD

**Issue by Raghead** [Ragowit/psn100#11127] opened 2023-02-17 16:15 UTC
**Game**
- https://psn100.net/game/13258-family-feud

**Information**
The online trophies are no longer unobtainable.
Ubisoft fixed the servers a while back.

- https://www.playstationtrophies.org/forum/topic/323329-trophy-boosting-thread-read-first-post/?do=findComment&comment=6566750
- https://forum.psnprofiles.com/topic/131013-online-not-working/?do=findComment&comment=2719763

**Comment by Ragowit** [comment] 2023-02-17 19:17
Thanks! I'm very behind with updating the status of unobtainable trophies. Been a lot with life(tm). I will however fix this later tonight.

**Comment by Ragowit** [comment] 2023-02-17 21:04
Going to close this issue as a duplicate of #10780, check that one for further info.

**Closed by Ragowit** 2023-02-17 21:04 UTC
Labels: duplicate, unobtainable trophies
